name: edaya_errand
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^1.5.4

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  injectable_generator: ^1.5.5

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf
